### ISSUE TITLE
Seed Error after running yarn seed

### ISSUE THREAD

**Issue by lokichaulagain** [mercurjs/mercur#3]
![image](https://github.com/mercurjs/mercur/assets/81034183/e6e12415-314c-427d-86fc-0201d5f8154b)

**Comment by cwierzbicki00** [comment]
Need to install the medusa cli. 

Make sure you have run yarn install in the api directory before installing.

Otherwise,

Run
```
yarn add @medusajs/medusa-cli
```

The readme set-up clearly assumes some prior medusa set-up knowledge. 

Once you get past this as well, the seed may fail with some error like 
```
Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

you can solve by adding 
```
"products": []
```
to the data/seed.json

I have just resolved this myself, will open PR sometime soon. Will also propose changes to the readme.

**Comment by NicolasGorga** [comment]
Experienced the same issue, solved it with @cwierzbicki00 let me know if you'll open the PR, otherwise i can gladly do it!

**Comment by gtomaka** [comment]
Thanks for sharing all info guys. The PR with fix is already merged.

When you configure a project, you need to execute yarn in /api as descibed in README.

**Comment by gtomaka** [comment]
✅
